buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		mavenCentral()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '[6.0,6.1)', changing: false
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'maven-publish'

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

minecraft {
	mappings channel: 'snapshot', version: '20210309-1.16.5'
	
	runs {
		client {
			workingDirectory project.file('run')
			property 'forge.logging.markers', 'REGISTRIES'
			property 'forge.logging.console.level', 'debug'
			mods {
				quickexp {
					source sourceSets.main
				}
			}
		}
	}
}

repositories {
	maven { url = 'https://maven.minecraftforge.net/' }
	mavenCentral()
}

dependencies {
	minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/mods.toml") {
		expand "version": inputs.properties.version
	}
}


java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}