org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05
minecraft_version=1.21.9

minecraft_version_range=[1.21.9,1.21.12)
neo_version=21.9.16-beta
loader_version_range=[1,)
neo_version_range=[21,)

mod_id=quickexp
mod_name=QuickExp
mod_license=MIT
mod_version=1.0.0

mod_group_id=cardejibka.quickexp
mod_authors=CardeJIbka
mod_description=A mod that allows rapid throwing of experience bottles by holding right-click.
